export const DEFAULT_CATEGORIES = [
  { name: 'Salary / Wages', type: 'income' },
  { name: 'Part Time', type: 'income' },
  { name: 'Investments', type: 'income' },
  { name: 'Refunds / Reimbursements', type: 'income' },
  { name: 'Business', type: 'income' },
  { name: 'Pension', type: 'income' },
  { name: 'Misc. Income', type: 'income' },

  { name: 'Rent', type: 'expense' },
  { name: 'Electricity', type: 'expense' },
  { name: 'Gas / Oil', type: 'expense' },
  { name: 'Water / Sewer / Trash', type: 'expense' },
  { name: 'Internet', type: 'expense' },
  { name: 'Furnishing / Appliances', type: 'expense' },
  { name: 'Home Maintenance / Improvements', type: 'expense' },
  { name: 'Tax', type: 'expense' },
  { name: 'Fuel', type: 'expense' },
  { name: 'Public Transportation', type: 'expense' },
  { name: 'Vehicle Repairs / Maintenance', type: 'expense' },
  { name: 'Groceries', type: 'expense' },
  { name: 'Eating Out', type: 'expense' },
  { name: 'Clothing', type: 'expense' },
  { name: 'Cleaning', type: 'expense' },
  { name: 'Bodycare & Barber', type: 'expense' },
  { name: 'Gym Membership', type: 'expense' },
  { name: 'Medicine / Supplement', type: 'expense' },
  { name: 'Entertainment', type: 'expense' },
  { name: 'Purchases', type: 'expense' },
  { name: 'Office / Business', type: 'expense' },
  { name: 'Misc. Expense', type: 'expense' },
]
